name: udacity-ml
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - numpy=1.16.4
  - pandas=0.25.1
  - python=3.7.4
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - seaborn=0.9.0
